### ISSUE TITLE
Calculadora de Calorias e Macronutrientes

### ISSUE THREAD

**Issue by leo-tavares** [leo-tavares/calculadora-X#2]
Os macronutrientes são compostos por carboidrato, proteína e gordura. As proteínas e carboidratos tem por volta de 4 calorias enquanto a gordura tem 9 calorias. 

Então para encontrarmos o valor total de calorias basta fazer

```js

const calorias = 4 * (carboidrato + proteina) + 9 * gordura

```

**Comment by Julia-Neves** [comment]
Implementações foram testadas, estilizações feitas e por fim, feito um merge na main. #3
