### ISSUE TITLE
Calculadora de IMC esta fazendo calculo quando não ha input

### ISSUE THREAD

**Issue by leo-tavares** [leo-tavares/calculadora-X#8]
# Como reproduzir?

- Clica no botão de imc
- Clica no botao de calcular sem informar qualquer input
- O resultado é "NaN"

# Resultado esperado

Talvez aparecer um alert pedindo para o usuário digitar um valor válido, o que acha @Paulo-oRicardo ?

**Comment by Paulo-oRicardo** [comment]
Corrigido, alert para inputs vazios
